### ISSUE TITLE
[UHN-MA-47] Vibrate/Ringtone for Snooze Screen

### ISSUE THREAD

**Issue by Asiapenguin** [CodetheChangeFoundation/UHN-Mobile-App#83]
- Add vibrate and/or ringtones (depends on whether the user is on vibrate mode or not) when we are on the last 15 seconds of the alarm.
  - This increases the likelihood of awakening a seemingly unconscious person. It is part of the specs

**Comment by ad2969** [comment]
It seems like there isn't an easy way to activate the phone's ringtone out there so far - except by having a 'sound player' which can load sound files and play them on command. I don't know if this is the approach we want to take, and if so, what sound we might consider using. Otherwise, vibrations work completely fine!

**Comment by Asiapenguin** [comment]
There is no way to just initiate the settings on the phone? i.e. if they are on vibrate, vibrate, if their system sound settings are on, use the ringtone they set in the OS?
